<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>siminspect_sim</name>
  <version>0.1.0</version>
  <description>Gazebo world and model resources for SimInspect-X.</description>
  <maintainer email="siminspect@example.com">SimInspect-X</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_cmake_pytest</test_depend>
  <test_depend>python3-opencv</test_depend>
  <test_depend>python3-pytest</test_depend>
  <test_depend>python3-yaml</test_depend>
  <test_depend>siminspect_gauge_vision</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
