slam_toolbox:
  ros__parameters:
    # Localization mode (pre-saved map)
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_loss_function: HuberLoss
    mode: localization
    map_file_name: ""  # set via launch arg
    map_start_pose: [0.0, 0.0, 0.0]
    map_start_at_dock: true
    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan
    odom_topic: /odometry/filtered
    # Localization
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.3
    transform_timeout: 0.2
    tf_buffer_duration: 30.0
    stack_size_to_use: 40000000
    do_loop_closing: false
