cmake_minimum_required(VERSION 3.8)
project(siminspect_description)
find_package(ament_cmake REQUIRED)
install(DIRECTORY urdf launch meshes config DESTINATION share/${PROJECT_NAME})
if(BUILD_TESTING)
  find_package(ament_cmake_pytest REQUIRED)
  ament_add_pytest_test(test_xacro_parse test/test_xacro_parse.py)
  ament_add_pytest_test(test_sensors test/test_sensors.py)
endif()
ament_package()
